name: draft_futbol
description: Draft Futbol

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.5+231

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  cart_stepper: ^4.0.0
  cloud_firestore: ^4.8.2
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.6.3
  firebase_core: ^2.14.0
  fl_animated_linechart: ^1.1.6
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.0
  flutter_native_splash: ^2.2.7
  flutter_riverpod: ^1.0.4
  flutter_spinkit: ^5.2.0
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^5.1.0
  google_mobile_ads: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  line_icons: ^2.0.1
  material_design_icons_flutter: ^5.0.6996
  multi_select_flutter: ^4.1.3
  path_provider: ^2.0.8
  purchases_flutter: ^3.10.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: "0.13.1"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/scores.ttf
    - assets/fonts/Inter-Black.ttf
    - assets/fonts/Inter-Bold.ttf
    - assets/fonts/Inter-ExtraBold.ttf
    - assets/fonts/Inter-ExtraLight.ttf
    - assets/fonts/Inter-Light.ttf
    - assets/fonts/Inter-Medium.ttf
    - assets/fonts/Inter-Regular.ttf
    - assets/fonts/Inter-SemiBold.ttf
    - assets/fonts/Inter-Thin.ttf
    - assets/images/kits/
    - assets/images/historic_kits/
    - assets/images/crests/
    - assets/images/pitch/
    - assets/images/league.png
    - assets/images/baguleyTrophy.png
    - assets/images/chairLeg.png
    - assets/images/baguleyLogo.png
    - assets/images/samGranger.png
    # New logo
    - assets/images/splash-screen.png
    - assets/images/1024_1024-icon.png
    - assets/images/app_icon.png
    - assets/images/logo2.png
    # - images/a_dot_ham.jpeg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter-Semi-Bold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: NbaAction
      fonts:
        - asset: assets/fonts/scores.ttf

flutter_native_splash:
  color: "#141618"
  image: assets/images/logo2.png
  android_disable_fullscreen: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#585858"
  adaptive_icon_background: "#585858"
