name: draft_futbol
description: Draft Futbol

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.0.1+402

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_custom_dropdown: 3.1.1
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  cart_stepper: ^4.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  fl_animated_linechart: ^1.1.6
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.0
  flutter_native_splash: ^2.2.7
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.0
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  line_icons: ^2.0.1
  material_design_icons_flutter: ^5.0.6996
  multi_select_flutter: ^4.1.3
  path_provider: ^2.0.8
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.4
  riverpod_annotation: 2.3.5
  go_router: ^9.0.3
  flutter_form_builder: ^8.0.0
  animated_toggle_switch: ^0.8.2


dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: "0.13.1"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.4.0
  custom_lint: 0.6.0 
  riverpod_lint: 2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/scores.ttf
    - assets/fonts/Inter-Black.ttf
    - assets/fonts/Inter-Bold.ttf
    - assets/fonts/Inter-ExtraBold.ttf
    - assets/fonts/Inter-ExtraLight.ttf
    - assets/fonts/Inter-Light.ttf
    - assets/fonts/Inter-Medium.ttf
    - assets/fonts/Inter-Regular.ttf
    - assets/fonts/Inter-SemiBold.ttf
    - assets/fonts/Inter-Thin.ttf
    - assets/images/kits/
    - assets/images/historic_kits/
    - assets/images/logos/
    - assets/images/pitch/
    - assets/images/league.png
    - assets/images/baguleyTrophy.png
    - assets/images/chairLeg.png
    - assets/images/baguleyLogo.png
    - assets/images/samGranger.png
    - assets/images/coffee.png
    - assets/images/coffee2.png
    # New logo
    - assets/images/splash-screen.png
    - assets/images/1024_1024-icon.png
    - assets/images/app_icon.png
    - assets/images/logo2.png
    - assets/images/play_store.png
    - assets/images/app_store.png
    - assets/images/substitution.png
    # - images/a_dot_ham.jpeg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter-Semi-Bold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: NbaAction
      fonts:
        - asset: assets/fonts/scores.ttf

flutter_native_splash:
  color: "#141618"
  image: assets/images/logo2.png
  android: true
  ios: true
  web: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#585858"
  adaptive_icon_background: "#585858"
