// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3rfnSARrCrw51saZkuofMz5sU3KKslA',
    appId: '1:639248146824:web:2c46e3143c4d30da2c1a3d',
    messagingSenderId: '639248146824',
    projectId: 'draft-futbol',
    authDomain: 'draft-futbol.firebaseapp.com',
    databaseURL: 'https://draft-futbol.firebaseio.com',
    storageBucket: 'draft-futbol.appspot.com',
    measurementId: 'G-CKY4E4R99Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2PxjCQrcl5iqMsiWqtjNyffLXFVHiBs',
    appId: '1:639248146824:android:f659359ed2e287762c1a3d',
    messagingSenderId: '639248146824',
    projectId: 'draft-futbol',
    databaseURL: 'https://draft-futbol.firebaseio.com',
    storageBucket: 'draft-futbol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0MOe0b-mgLs-zgKvdtsYabBE5Dxb6aGI',
    appId: '1:639248146824:ios:27187ad30bb3ae502c1a3d',
    messagingSenderId: '639248146824',
    projectId: 'draft-futbol',
    databaseURL: 'https://draft-futbol.firebaseio.com',
    storageBucket: 'draft-futbol.appspot.com',
    iosClientId: '639248146824-uqc5dhpkvie3rt335fh4ulk79fai9j0h.apps.googleusercontent.com',
    iosBundleId: 'com.psjmcneill.draftfutbol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0MOe0b-mgLs-zgKvdtsYabBE5Dxb6aGI',
    appId: '1:639248146824:ios:27187ad30bb3ae502c1a3d',
    messagingSenderId: '639248146824',
    projectId: 'draft-futbol',
    databaseURL: 'https://draft-futbol.firebaseio.com',
    storageBucket: 'draft-futbol.appspot.com',
    iosClientId: '639248146824-uqc5dhpkvie3rt335fh4ulk79fai9j0h.apps.googleusercontent.com',
    iosBundleId: 'com.psjmcneill.draftfutbol',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
